// Add new sites here. status: "done" = show card, "in-progress" = hidden (tracked only)
// muxId: Mux playback ID — shows looping video preview with image crossfade
export const sites = [
  {
    slug: "blais",
    href: "https://www.blaiscameron.com/",
    title: "Blais Cameron Films",
    description: "Portfolio for a film studio.",
    preview: "/assets/previews/blais.jpg",
    muxId: "I6DUXZ2MJ3E801MUk021jQkAFPixNrzHiCm5cKDyBHVe8",
    tags: ["NEXT.JS", "RAPID PROJECT"],
    status: "done",
  },
  {
    slug: "project96",
    href: "https://www.project96.com/",
    title: "Project 96",
    description: "Diaspora World Cup activation series, NYC 2026.",
    preview: "/assets/previews/project96.png",
    muxId: null,
    tags: ["EVENT SITE", "NEXT.JS"],
    status: "done",
  },
  {
    slug: "sams-cybersecurity",
    href: null,
    title: "Sam's Cybersecurity",
    description: "A site for a small cybersecurity business.",
    preview: null,
    muxId: null,
    tags: [],
    status: "in-progress",
  },
  {
    slug: "comotion-2024",
    href: "https://launch-comotion2024.byamadeus.com/",
    title: "2024 SCAD CoMotion",
    description: "SCAD's annual motion design conference.",
    preview: "/assets/previews/comotion-2024.png",
    muxId: "HYtqQsn4L101XtM2Au1U3lHf2rFJw7AWbZFBmBEjQscU",
    tags: ["EVENT SITE", "WEBFLOW"],
    status: "done",
  },
  {
    slug: "startup-2024",
    href: "https://2024-startup.byamadeus.com/",
    title: "2024 SCAD StartUp",
    description: "SCAD's annual startup pitch competition.",
    preview: "/assets/previews/startup-2024.png",
    muxId: "IUMwDO7CvFuk46VS6YfKPFFslJSeh02aNBafu7H01pbPQ",
    tags: ["EVENT SITE", "WEBFLOW"],
    status: "done",
  },
  {
    slug: "comotion-2023",
    href: "https://comotion-2023.vercel.app/",
    title: "2023 SCAD CoMotion",
    description: "SCAD's annual motion design conference.",
    preview: "/assets/previews/comotion-2023.png",
    muxId: "x00bt00HC4hS1bUhgAXxw02802OYem4olu1DlD5gLnmoMcQ",
    tags: ["EVENT SITE", "WEBFLOW"],
    status: "done",
  },
  {
    slug: "startup-2023",
    href: "https://2023-startup.byamadeus.com/",
    title: "2023 SCAD StartUp",
    description: "SCAD's annual startup pitch competition.",
    preview: "/assets/previews/startup-2023.png",
    muxId: "1MWKPIAygt4sltPshD1vS01LJApBAhBabqAd2nj1W7O8",
    tags: ["EVENT SITE", "WEBFLOW", "RAPID PROJECT"],
    status: "done",
  },
];
