// Add new sites here. status: "done" = show card, "in-progress" = hidden (tracked only)
export const sites = [
  {
    slug: "blais",
    href: "https://www.blaiscameron.com/",
    title: "Blais Cameron Films",
    description: "Portfolio for a film studio.",
    preview: "/assets/previews/blais.jpg",
    tags: ["NEXT.JS", "RAPID PROJECT"],
    status: "done",
  },
  {
    slug: "sams-cybersecurity",
    href: null,
    title: "Sam's Cybersecurity",
    description: "A site for a small cybersecurity business.",
    preview: null,
    tags: [],
    status: "in-progress",
  },
  {
    slug: "comotion-2024",
    href: "https://launch-comotion2024.byamadeus.com/",
    title: "2024 SCAD CoMotion",
    description: "SCAD's annual motion design conference.",
    preview: "/assets/previews/comotion-2024.png",
    tags: ["EVENT SITE", "WEBFLOW"],
    status: "done",
  },
  {
    slug: "startup-2024",
    href: "https://2024-startup.byamadeus.com/",
    title: "2024 SCAD StartUp",
    description: "SCAD's annual startup pitch competition.",
    preview: "/assets/previews/startup-2024.png",
    tags: ["EVENT SITE", "WEBFLOW"],
    status: "done",
  },
  {
    slug: "comotion-2023",
    href: "https://comotion-2023.vercel.app/",
    title: "2023 SCAD CoMotion",
    description: "SCAD's annual motion design conference.",
    preview: "/assets/previews/comotion-2023.png",
    tags: ["EVENT SITE", "WEBFLOW"],
    status: "done",
  },
  {
    slug: "startup-2023",
    href: "https://2023-startup.byamadeus.com/",
    title: "2023 SCAD StartUp",
    description: "SCAD's annual startup pitch competition.",
    preview: "/assets/previews/startup-2023.png",
    tags: ["EVENT SITE", "WEBFLOW", "RAPID PROJECT"],
    status: "done",
  },
];
